name: Self Hosted Runner

on:
  workflow_dispatch:
jobs:
  build:
    runs-on: self-hosted
    steps:
      - name: Checkout the code
        uses: actions/checkout@v2
      - name: Run the script
        run: echo "Hello Self running server"
